### ISSUE TITLE
Arrow Not Working

### ISSUE THREAD

**Issue by bpPrg** [uclmr/egal#3] opened 2017-09-06 00:05 UTC
First of all, I would like to thank you for creating this wonderful widget.
But, I got a problem using this widget. The rectangle and circle works, but the arrow does not work for me.

Platform: MacOS Sierra. (MacPro 13'' with touchbar)
jupyter --version
4.3.0

**Comment by riedelcastro** [comment] 2017-09-06 16:08
Thanks for your feedback! 

I will try to look into this within the next 2-3 weeks. Unfortunately, I am really swamped right now.

**Comment by undwie** [comment] 2017-11-06 22:51
It might be that the arrow is a little tricky to use: you have to click on one of the "circles" that appear when you hover over the object (rectangle, circle), and then click on it. This starts the arrow. Then you need to click on a connector-circle on another object.  Note that right now the "arrows" have to be connectors---they cannot end "in space". Have you tried this?

**Comment by riedelcastro** [comment] 2017-11-08 19:05
I close this for now because I can't reproduce it. Let me know if what I wrote above helps. If not, we can re-open the issue.

**Closed as completed by riedelcastro** 2017-11-08 19:05 UTC
